on: push
jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build for linux/amd64
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          platforms: linux/amd64
          tags: cs50/mysql:amd64
          cache-from: type=registry,ref=cs50/mysql:amd64-buildcache
          cache-to: type=registry,ref=cs50/mysql:amd64-buildcache,mode=max

      - name: Push linux/amd64 build to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/mysql:amd64

      - name: Build for linux/arm64
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          platforms: linux/arm64
          tags: cs50/mysql:arm64
          cache-from: type=registry,ref=cs50/mysql:arm64-buildcache
          cache-to: type=registry,ref=cs50/mysql:arm64-buildcache,mode=max

      - name: Push linux/arm64 build to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/mysql:arm64

      - name: Create multi-arch manifest and push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker manifest create cs50/mysql:latest \
          --amend cs50/mysql:amd64 \
          --amend cs50/mysql:arm64
          docker manifest create cs50/mysql:8 \
          --amend cs50/mysql:amd64 \
          --amend cs50/mysql:arm64
          docker manifest push cs50/mysql:latest
          docker manifest push cs50/mysql:8

